---
- name: Config backup server
  hosts: all
  become: true

  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: epel-release

    - name: Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
          - vim
          - borgbackup

    - name: Create borg group
      ansible.builtin.group:
        name: borg
        state: present

    - name: Create borg user
      ansible.builtin.user:
        name: borg
        group: borg
        state: present

    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/borg/.ssh
        state: directory
        mode: "0700"
        owner: borg
        group: borg

    - name: Create authorized_keys file
      ansible.builtin.file:
        path: /home/borg/.ssh/authorized_keys
        state: touch
        mode: "0600"
        owner: borg
        group: borg

    - name: Add authorized key
      ansible.builtin.lineinfile:
        path: /home/borg/.ssh/authorized_keys
        line: "{{ lookup('file', 'ssh/id_rsa.pub') }}"
        create: true

    - name: Create backup directory
      ansible.builtin.file:
        path: /var/backup
        state: directory
        owner: borg
        group: borg
