---
# tasks file for dhcp_pxe

#Копирование файла конфигурации DHCP-сервера
- name: set up dhcp-server
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: '0644'
  notify: 
  - restart dhcp-server
