Vagrant.configure('2') do |config|
  (1..1).each do |i|
  config.vm.define "Systemd" do |machine|
    machine.vm.box = 'centos/7'
    machine.vm.network "private_network", ip: '192.168.56.3'
    machine.vm.hostname = "Systemd"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "Systemd-#{i}"
      vb.cpus = '2'
      vb.memory = '1024'
    end
  end
  end
end
