# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure('2') do |config|
  (1..1).each do |i|
  config.vm.define "webserver" do |machine|
    machine.vm.box = 'centos/7'
    machine.vm.hostname = "webserver"
    machine.vm.provider "hyperv" do |vb|
      vb.name = "webserver_nginx-#{i}"
      vb.cpus = '8'
      vb.memory = '65365'
    end
      config.vm.provision "shell", path: "config.sh"   
    end
  end
end
