MACHINES = {
  :"pam" => {
              :box_name => "centos/7",
              :cpus => 2,
              :memory => 1024,
              :ip => "192.168.57.10",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "private_network", ip: boxconfig[:ip]
    config.vm.define boxname do |box|
     box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      #копируем с хоста скрипт
     # box.vm.provision "file", source: "/home/mity/Documents/OTUS_Linux_Prof/Lesson22/login.sh", destination: "/tmp/"
      box.vm.provision "shell", inline: <<-SHELL
          #Разрешаем подключение пользователей по SSH с использованием пароля
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          #Добавляем пользователей, назначаем пароли, создаём группы   
          sudo useradd otusadm && sudo useradd otus
          echo "Otus2022!" | sudo passwd --stdin otusadm && echo "Otus2022!" | sudo passwd --stdin otus
          sudo groupadd -f admin
          sudo usermod otusadm -a -G admin
          sudo usermod root -a -G admin
          sudo usermod vagrant -a -G admin
          sudo cp /tmp/login.sh /usr/local/bin/
          #Добавляем скрипту права на запуск
          sudo chmod +x /usr/local/bin/login.sh		
          #Перезапуск службы SSHD
          systemctl restart sshd.service
	  SHELL
    end
  end
end
