# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.10',
        :path => 'server.sh'        
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.network "private_network", ip: boxconfig[:ip_addr]
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh 
                sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                systemctl restart sshd
                systemctl restart network
                sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
                setenforce 0
                yum install -y epel-release
                yum install -y openvpn easy-rsa
                yum install -y sshpass 
        SHELL
        
        box.vm.provision  "shell", path: boxconfig[:path]
        
        
      end

  end
end
