Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # config.vm.box_check_update = false

  config.vm.network "public_network", ip: "192.168.88.190"

  # config.vm.network "public_network"

   config.vm.synced_folder ".", "/Ansible", disabled: true
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
    vb.name = 'webserver_nginx'
    vb.cpus = '2'
    vb.memory = '1024'     
   end
end
