# -*- mode: ruby -*- 
# vi: set ft=ruby : vsa
Vagrant.configure(2) do |config| 
 config.vm.box = "centos/7" 
 config.vm.box_version = "2004.01" 
 config.vm.provider "virtualbox" do |v| 
 v.memory = 256 
 v.cpus = 1 
end 
 config.vm.define "nfss" do |nfss| 
 nfss.vm.network "private_network", ip: "172.16.0.20",  virtualbox__intnet: "net1" 
 nfss.vm.hostname = "nfss" 
 config.vm.provision "shell", path: "server.sh"
end 
 config.vm.define "nfsc" do |nfsc| 
 nfsc.vm.network "private_network", ip: "172.16.0.25",  virtualbox__intnet: "net1" 
 nfsc.vm.hostname = "nfsc" 
 config.vm.provision "shell", path: "client.sh" 
 end 
end 
 
