---
- name: Config centralRouter
  hosts: all
  become: true

  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: epel-release

    - name: Install packages
      ansible.builtin.yum:
        name:
          - vim
          - traceroute
          - nmap

    # --- Forwarding

    - name: Set up forward packages across routers
      ansible.builtin.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    # --- Set default route via inetRouter

    - name: Disable default route
      ansible.builtin.lineinfile: 
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: DEFROUTE="no"

    - name: Add default gateway for centralRouter
      ansible.builtin.lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.255.1 

    - name: Add static route for office1
      ansible.builtin.lineinfile:
        dest: /etc/sysconfig/network-scripts/route-eth5
        create: true
        line: 192.168.2.128/26 via 192.168.255.10

    - name: Add static route for office2
      ansible.builtin.lineinfile:
        dest: /etc/sysconfig/network-scripts/route-eth6
        create: true
        line: 192.168.1.0/25 via 192.168.255.6

    # --- Странная штука: маршрут по умолчанию прописывается корректно
    #     только после второго перезапуска сети o_0

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted

    # --- SSH

    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        mode: "0700"
        owner: vagrant
        group: vagrant

    - name: Add ssh keys
      ansible.builtin.copy:
        src: ssh/
        dest: /home/vagrant/.ssh/
        mode: "0600"
        owner: vagrant
        group: vagrant

    # --- Knock

    - name: Add knock script
      ansible.builtin.copy:
        src: files/knock.sh
        dest: /home/vagrant/knock.sh
        mode: "0755"
        owner: vagrant
        group: vagrant
