---
- name: Config inetRouter
  hosts: all
  become: true

  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: epel-release

    # --- IP Tables

    - name: Install packages
      ansible.builtin.yum:
        name:
          - vim
          - traceroute
          - iptables
          - iptables-services
        state: present
        update_cache: true

    - name: Copy iptables config
      ansible.builtin.template:
        src: files/iptables-inetRouter.rules
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: "0600"

    - name: Start and enable iptables service
      ansible.builtin.service:
        name: iptables
        state: restarted
        enabled: true

    # --- Forwarding

    - name: Set up forward packages across routers
      ansible.builtin.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    # --- Static route

    - name: Add static route
      ansible.builtin.blockinfile:
        path: /etc/sysconfig/network-scripts/route-eth1
        create: true
        block: |
          192.168.0.0/22 via 192.168.255.2
          192.168.255.4/30 via 192.168.255.2
          192.168.255.8/30 via 192.168.255.2

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted

    # --- SSH access

    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        mode: "0700"
        owner: vagrant
        group: vagrant

    - name: Copy authorized_keys file
      ansible.builtin.file:
        path: /home/vagrant/.ssh/authorized_keys
        state: touch
        mode: "0600"
        owner: vagrant
        group: vagrant

    - name: Add authorized key
      ansible.builtin.lineinfile:
        path: /home/vagrant/.ssh/authorized_keys
        line: "{{ lookup('file', 'ssh/id_rsa.pub') }}"
        create: true

    # --- Knockd

    - name: Install knockd
      ansible.builtin.yum:
        name:
          - knock-server
        state: present

    - name: Add ssh keys
      ansible.builtin.copy:
        src: files/knockd.conf
        dest: /etc/knockd.conf
        mode: "0664"
        owner: root
        group: root

    - name: set up repo
      ansible.builtin.replace:
        path: /usr/lib/systemd/system/knockd.service
        regexp: 'ExecStart=.*'
        replace: "ExecStart=/usr/sbin/knockd -i eth1 -d $OPTIONS"

    - name: Start and enable knockd service
      ansible.builtin.service:
        name: knockd
        state: restarted
        enabled: true
