Vagrant.configure('2') do |config|
  (1..1).each do |i|
  config.vm.define "webserver" do |machine|
    machine.vm.box = 'centos/7'
    machine.vm.hostname = "webserver"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "webserver_nginx-#{i}"
      vb.cpus = '2'
      vb.memory = '1024'
    end
  end
  end
end
